name: Frequent Daily Commit

on:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时运行一次
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 更新到v3版本

      - name: Create file with current time
        run: |
          DATE=$(date +%Y%m%d_%H%M)  # 包含小时分钟以区分文件
          TIME=$(date +%H:%M)
          echo "$TIME" > "${DATE}.txt"
          echo "Created file: ${DATE}.txt"
          ls -la

      - name: Commit and push changes
        run: |
          git config --local user.name "AMWss"
          git config --local user.email "2172888206@qq.com"
          DATE=$(date +%Y%m%d_%H%M)
          git add "${DATE}.txt"
          git commit -m "自动提交：添加 ${DATE}.txt"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete half of the files every other day
        #if: ${{ github.event.schedule }} # 只有在定时任务中执行此步骤
        run: |
          # 检查是否是需要删除文件的时间
          DAY=$(date +%d)  # 获取当前日期的天
          if [ $((DAY % 2)) -eq 0 ]; then
            echo "今天需要删除一半的文件。"
            
            # 获取所有文件并计算数量
            FILES=($(ls *.txt))
            TOTAL_FILES=${#FILES[@]}
            
            # 计算需要删除的文件数量
            DELETE_COUNT=$((TOTAL_FILES / 2))
            echo "总文件数量: $TOTAL_FILES"
            echo "需要删除的文件数量: $DELETE_COUNT"
            
            # 删除文件
            for ((i = 0; i < DELETE_COUNT; i++)); do
              echo "Deleting: ${FILES[i]}"
              rm -f "${FILES[i]}"
            done
            
            # 提交更改
            git add .
            git commit -m "自动提交：删除一半的文件"
            git push
          else
            echo "今天不需要删除文件。"
          fi
